name: Kairaa CRD Linux (Official Repo)

on:
  workflow_dispatch:
    inputs:
      crd_auth_code:
        description: 'Tempel Kode Otorisasi CRD untuk Debian Linux di sini'
        required: true
        type: string

jobs:
  secure-crd:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CRD and Desktop via Official Google Repository
        run: |
          # --- METODE BARU: Menambahkan Repositori Resmi Google ---
          # Ini adalah cara paling andal untuk menginstal perangkat lunak Google.
          
          # 1. Unduh dan impor kunci penandatanganan paket Google
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-chrome-keyring.gpg
          
          # 2. Tambahkan Repositori Google Chrome ke daftar sumber apt
          # (Chrome Remote Desktop ada di dalam repositori ini)
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          
          # 3. Perbarui daftar paket untuk menyertakan paket dari repositori baru
          sudo apt-get update
          
          # 4. Instal CRD dan XFCE. apt sekarang akan menemukan CRD dari server Google.
          sudo apt-get install --assume-yes chrome-remote-desktop xfce4 desktop-base dbus-x11 xscreensaver
          
          echo "Instalasi melalui repositori resmi selesai."

      - name: Verify CRD Installation
        run: |
          # Langkah verifikasi ini sekarang HARUS berhasil.
          echo "Memeriksa keberadaan file crd-auth..."
          ls -l /opt/google/chrome-remote-desktop/crd-auth
          echo "Instalasi CRD berhasil diverifikasi."

      - name: Configure and Authorize Chrome Remote Desktop
        run: |
          CRD_USER=$(whoami)
          echo "Mengkonfigurasi untuk pengguna: $CRD_USER"
          
          echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" | sudo tee /home/$CRD_USER/.chrome-remote-desktop-session
          sudo chown $CRD_USER:$CRD_USER /home/$CRD_USER/.chrome-remote-desktop-session
          
          CRD_AUTH_CODE="${{ github.event.inputs.crd_auth_code }}"
          
          sudo -u $CRD_USER bash -c "/opt/google/chrome-remote-desktop/crd-auth --code='$CRD_AUTH_CODE'"

          echo "Otorisasi CRD berhasil."

      - name: Start Chrome Remote Desktop Service
        run: |
          sudo systemctl start chrome-remote-desktop@$USER
          echo "Layanan Chrome Remote Desktop telah dimulai."
          
      - name: Maintain Connection
        run: |
          echo -e "\n===================================================================="
          echo "  VM ANDA SEKARANG SIAP DIAKSES"
          echo ""
          echo "  1. Buka browser Anda dan pergi ke:"
          echo "     https://remotedesktop.google.com/access"
          echo ""
          echo "  2. Anda akan melihat runner GitHub ini muncul sebagai mesin online."
          echo ""
          echo "  3. Klik untuk terhubung!"
          echo "====================================================================\n"

          # Jaga agar runner tetap aktif
          sleep 21600
