name: Kairaa CRD Linux (Robust)

on:
  workflow_dispatch:
    inputs:
      crd_auth_code:
        description: 'Tempel Kode Otorisasi CRD untuk Debian Linux di sini'
        required: true
        type: string

jobs:
  secure-crd:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CRD, Desktop, and All Dependencies in One Step
        run: |
          sudo apt-get update
          wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
          
          # --- PERBAIKAN KRUSIAL: Gabungkan semua instalasi ke dalam satu perintah 'apt' ---
          # Ini memungkinkan 'apt' untuk menyelesaikan semua dependensi secara bersamaan,
          # membuatnya jauh lebih andal daripada beberapa perintah terpisah.
          sudo apt install --assume-yes ./chrome-remote-desktop_current_amd64.deb \
              xfce4 \
              desktop-base \
              dbus-x11 \
              xscreensaver
          
          echo "Instalasi gabungan selesai."

      - name: Verify CRD Installation
        run: |
          # --- LANGKAH PENTING: Verifikasi bahwa file kunci benar-benar ada ---
          # Langkah ini akan gagal jika instalasi sebelumnya tidak berhasil,
          # memberikan kita diagnosis yang jelas.
          echo "Memeriksa keberadaan file crd-auth..."
          ls -l /opt/google/chrome-remote-desktop/crd-auth
          
          echo "Verifikasi direktori /opt/google..."
          ls -l /opt/google
          
          echo "Verifikasi direktori /opt/google/chrome-remote-desktop..."
          ls -l /opt/google/chrome-remote-desktop
          
          echo "Instalasi CRD berhasil diverifikasi."

      - name: Configure and Authorize Chrome Remote Desktop
        run: |
          CRD_USER=$(whoami)
          echo "Mengkonfigurasi untuk pengguna: $CRD_USER"
          
          echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" | sudo tee /home/$CRD_USER/.chrome-remote-desktop-session
          sudo chown $CRD_USER:$CRD_USER /home/$CRD_USER/.chrome-remote-desktop-session
          
          CRD_AUTH_CODE="${{ github.event.inputs.crd_auth_code }}"
          
          # Jalankan perintah otorisasi menggunakan path absolut
          sudo -u $CRD_USER bash -c "/opt/google/chrome-remote-desktop/crd-auth --code='$CRD_AUTH_CODE'"

          echo "Otorisasi CRD berhasil."

      - name: Start Chrome Remote Desktop Service
        run: |
          sudo systemctl start chrome-remote-desktop@$USER
          echo "Layanan Chrome Remote Desktop telah dimulai."
          
      - name: Maintain Connection
        run: |
          echo -e "\n===================================================================="
          echo "  VM ANDA SEKARANG SIAP DIAKSES"
          echo ""
          echo "  1. Buka browser Anda dan pergi ke:"
          echo "     https://remotedesktop.google.com/access"
          echo ""
          echo "  2. Anda akan melihat runner GitHub ini muncul sebagai mesin online."
          echo ""
          echo "  3. Klik untuk terhubung!"
          echo "====================================================================\n"

          # Jaga agar runner tetap aktif
          sleep 21600
