name: AiraaCheisyaa CRD (VirtualBox & Performance Boost + Debian ISO)

on:
  workflow_dispatch:
    inputs:
      crd_full_command:
        description: 'Salin dan tempel SELURUH perintah dari halaman CRD Headless (CMD atau PowerShell)'
        required: true

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 4320
    env:
      CRD_USER_PASSWORD: ${{ secrets.CRD_USER_PASSWORD }}
      INSTALLER_CACHE_PATH: C:\cached-installers
      DEBIAN_ISO_FILENAME: debian-13.1.0-amd64-DVD-1.iso

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Cached Installers and ISO
        id: cache-restore
        uses: actions/cache@v4
        with:
          path: ${{ env.INSTALLER_CACHE_PATH }}
          key: ${{ runner.os }}-installers-v2-${{ env.DEBIAN_ISO_FILENAME }}

      - name: Rename Runner User to AiraaCheisyaa and Set Password
        shell: pwsh
        run: |
          $password = if ($env:CRD_USER_PASSWORD -and $env:CRD_USER_PASSWORD.Trim() -ne "") { $env:CRD_USER_PASSWORD } else { "ChangeThisPassword123!" }
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          Write-Host "Mengganti nama pengguna 'runneradmin' menjadi 'AiraaCheisyaa'..."
          Rename-LocalUser -Name "runneradmin" -NewName "AiraaCheisyaa"
          Write-Host "Mengatur kata sandi untuk 'AiraaCheisyaa'..."
          Set-LocalUser -Name "AiraaCheisyaa" -Password $securePass
          echo "WINDOWS_PASSWORD=$password" >> $env:GITHUB_ENV

      - name: Prepare directories
        shell: pwsh
        run: |
          New-Item -Path C:\AiraaCheisyaa -ItemType Directory -Force | Out-Null
          New-Item -Path C:\AiraaCheisyaa\ISO -ItemType Directory -Force | Out-Null
          New-Item -Path C:\AiraaCheisyaa\logs -ItemType Directory -Force | Out-Null
          if (-not (Test-Path "${{ env.INSTALLER_CACHE_PATH }}")) {
            New-Item -Path "${{ env.INSTALLER_CACHE_PATH }}" -ItemType Directory -Force | Out-Null
          }

      - name: Install Pre-requisite Software & Enable CRD Install Logging
        shell: pwsh
        run: |
          $vscodePath = Join-Path "${{ env.INSTALLER_CACHE_PATH }}" "vscode_installer.exe"
          $vboxPath = Join-Path "${{ env.INSTALLER_CACHE_PATH }}" "virtualbox_installer.exe"
          $crdPath = Join-Path "${{ env.INSTALLER_CACHE_PATH }}" "crd.msi"

          # Install VSCode & VirtualBox
          if (-not (Test-Path $vscodePath)) { Invoke-WebRequest -Uri "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user" -OutFile $vscodePath }
          Start-Process -FilePath $vscodePath -ArgumentList '/verysilent /mergetasks=!runcode' -Wait
          if (-not (Test-Path $vboxPath)) { Invoke-WebRequest -Uri "https://download.virtualbox.org/virtualbox/7.0.18/VirtualBox-7.0.18-162988-Win.exe" -OutFile $vboxPath }
          Start-Process -FilePath $vboxPath -ArgumentList '--silent --ignore-reboot' -Wait

          # Install CRD dengan logging verbose diaktifkan
          if (-not (Test-Path $crdPath)) { Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile $crdPath }
          $logPath = "C:\AiraaCheisyaa\logs\crd_install.log"
          Write-Host "Starting CRD installation with verbose logging to $logPath..."
          Start-Process -FilePath "msiexec.exe" -ArgumentList "/i `"$crdPath`" /qn /norestart /L*v `"$logPath`"" -Wait
          Write-Host "msiexec process has finished."

      - name: 🔍 Run Post-Installation Diagnostics
        shell: pwsh
        run: |
          Write-Host "--- Verifying Installation Contents ---"
          Write-Host ""
          Write-Host "Listing top-level directories in C:\Program Files..."
          Get-ChildItem -Path "C:\Program Files" -Directory | ForEach-Object { Write-Host " -> $($_.Name)" }
          Write-Host ""
          Write-Host "Listing top-level directories in C:\Program Files (x86)..."
          Get-ChildItem -Path "C:\Program Files (x86)" -Directory | ForEach-Object { Write-Host " -> $($_.Name)" }
          Write-Host ""

          $crdExeFile = Get-ChildItem -Path "C:\Program Files", "C:\Program Files (x86)" -Filter "remoting_start_host.exe" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
          if ($null -ne $crdExeFile) {
              Write-Host "SUCCESS: Found remoting_start_host.exe at $($crdExeFile.FullName)"
          } else {
              Write-Error "FAILURE: Did not find remoting_start_host.exe anywhere."
              # Keluar dengan kode galat untuk memastikan workflow berhenti jika file tidak ada
              exit 1
          }

      # Langkah-langkah lain sengaja dilewati untuk fokus pada diagnostik
      # ...

      - name: 📤 Upload Installation Logs
        if: always() # WAJIB: Jalankan ini bahkan jika langkah sebelumnya gagal
        uses: actions/upload-artifact@v4
        with:
          name: crd-install-logs
          path: C:\AiraaCheisyaa\logs\
