name: AiraaCheisyaa CRD (Auto Extract Code)

on:
  workflow_dispatch:
    inputs:
      crd_full_command:
        description: 'Salin dan tempel SELURUH perintah dari halaman CRD Headless (CMD atau PowerShell)'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Create User AiraaCheisyaa
        run: |
          $password = "ChangeThisPassword123!"
          New-LocalUser -Name "AiraaCheisyaa" -Password (ConvertTo-SecureString $password -AsPlainText -Force)
          Add-LocalGroupMember -Group "Administrators" -Member "AiraaCheisyaa"
          echo "WINDOWS_PASSWORD=$password" >> $env:GITHUB_ENV
        shell: pwsh

      - name: Download and Install Essential Software
        run: |
          Write-Host "Mengunduh dan menginstal Google Chrome..."
          Invoke-WebRequest -Uri "https://dl.google.com/chrome/install/stable/current/chrome_installer.exe" -OutFile "$env:TEMP\chrome_installer.exe"
          Start-Process -FilePath "$env:TEMP\chrome_installer.exe" -ArgumentList "/silent /install" -Wait
          
          Write-Host "Mengunduh dan menginstal Visual Studio Code..."
          Invoke-WebRequest -Uri "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user" -OutFile "$env:TEMP\vscode_installer.exe"
          Start-Process -FilePath "$env:TEMP\vscode_installer.exe" -ArgumentList '/verysilent /mergetasks=!runcode' -Wait

          Write-Host "Mengunduh dan menginstal Chrome Remote Desktop..."
          Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "crd.msi"
          Start-Process msiexec.exe -Wait -ArgumentList '/i crd.msi /qn'
        shell: pwsh
      
      - name: Extract Code and Start Chrome Remote Desktop Host
        run: |
          # Mengambil seluruh perintah yang Anda tempel dari input
          $FullCommand = '${{ github.event.inputs.crd_full_command }}'
          
          # Pola untuk mencari kode di antara --code="..."
          $Pattern = '--code="(.+?)"'
          
          $AuthCode = ""
          if ($FullCommand -match $Pattern) {
              # Jika pola ditemukan, ambil kodenya
              $AuthCode = $matches[1]
              Write-Host "Authorization code extracted successfully."
          } else {
              # Jika pola tidak ditemukan, gagalkan alur kerja
              Write-Error "Could not find authorization code in the provided command. Please paste the full command."
              exit 1
          }
          
          # Menjalankan perintah dengan kode yang sudah diekstrak
          $PIN = "123456"
          $HostName = "gh-runner-${{ github.run_id }}"
          & "C:\Program Files (x86)\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="$AuthCode" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name="$HostName" -pin="$PIN"
          
          Write-Host "=========================== CREDENTIALS ==========================="
          Write-Host "Host Name: $HostName"
          Write-Host "Windows User: AiraaCheisyaa"
          Write-Host "Windows Password: $env:WINDOWS_PASSWORD"
          Write-Host "CRD PIN: $PIN"
          Write-Host "====================================================================="
        shell: pwsh

      - name: Keep Runner Alive
        run: |
          Write-Host "Sesi RDP aktif. Tutup jendela workflow secara manual untuk mengakhiri."
          Start-Sleep -Seconds 21600 # Tetap aktif selama 6 jam (batas maksimal GitHub)
        shell: pwsh
