name: AiraaCheisyaa CRD with Input

on:
  workflow_dispatch:
    inputs:
      crd_auth_code:
        description: 'Your CRD Authorization Code (e.g., 4/xxxx...)'
        required: true

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Create User AiraaCheisyaa
        run: |
          $password = "ChangeThisPassword123!"
          New-LocalUser -Name "AiraaCheisyaa" -Password (ConvertTo-SecureString $password -AsPlainText -Force)
          Add-LocalGroupMember -Group "Administrators" -Member "AiraaCheisyaa"
          echo "WINDOWS_PASSWORD=$password" >> $env:GITHUB_ENV

      - name: Download and Install Chrome Remote Desktop
        run: Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "crd.msi" && Start-Process msiexec.exe -Wait -ArgumentList '/i crd.msi /qn'
      
      - name: Start Chrome Remote Desktop Host
        run: |
          $PIN = "123456"
          $HostName = "gh-runner-${{ github.run_id }}"
          $AuthCode = "${{ github.event.inputs.crd_auth_code }}"
          & "C:\Program Files (x86)\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="$AuthCode" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name="$HostName" -pin="$PIN"
          
          Write-Host "=========================== CREDENTIALS ==========================="
          Write-Host "Host Name: $HostName"
          Write-Host "Windows User: AiraaCheisyaa"
          Write-Host "Windows Password: $env:WINDOWS_PASSWORD"
          Write-Host "CRD PIN: $PIN"
          Write-Host "====================================================================="

      - name: Keep Runner Alive
        run: Start-Sleep -Seconds 21000 # Keep alive for ~5.8 hours
