name: AiraaCheisyaa CRD (VirtualBox & Performance Boost + Debian ISO)

on:
  workflow_dispatch:
    inputs:
      crd_full_command:
        description: 'Salin dan tempel SELURUH perintah dari halaman CRD Headless (CMD atau PowerShell)'
        required: true

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 4320
    env:
      CRD_USER_PASSWORD: ${{ secrets.CRD_USER_PASSWORD }}
      INSTALLER_CACHE_PATH: C:\cached-installers
      DEBIAN_ISO_FILENAME: debian-13.1.0-amd64-DVD-1.iso

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Cached Installers and ISO
        id: cache-restore
        uses: actions/cache@v4
        with:
          path: ${{ env.INSTALLER_CACHE_PATH }}
          key: ${{ runner.os }}-installers-v3-${{ env.DEBIAN_ISO_FILENAME }}

      - name: Prepare Dirs and Install All Software
        shell: pwsh
        run: |
          # Siapkan Direktori
          New-Item -Path C:\AiraaCheisyaa -ItemType Directory -Force | Out-Null
          if (-not (Test-Path "${{ env.INSTALLER_CACHE_PATH }}")) {
            New-Item -Path "${{ env.INSTALLER_CACHE_PATH }}" -ItemType Directory -Force | Out-Null
          }

          # Instal Perangkat Lunak SEBELUM mengubah nama pengguna
          Write-Host "Installing software as default runner user..."
          $vscodePath = Join-Path "${{ env.INSTALLER_CACHE_PATH }}" "vscode_installer.exe"
          $vboxPath = Join-Path "${{ env.INSTALLER_CACHE_PATH }}" "virtualbox_installer.exe"
          $crdPath = Join-Path "${{ env.INSTALLER_CACHE_PATH }}" "crd.msi"

          if (-not (Test-Path $vboxPath)) { Invoke-WebRequest -Uri "https://download.virtualbox.org/virtualbox/7.0.18/VirtualBox-7.0.18-162988-Win.exe" -OutFile $vboxPath }
          Start-Process -FilePath $vboxPath -ArgumentList '--silent --ignore-reboot' -Wait
          
          if (-not (Test-Path $crdPath)) { Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile $crdPath }
          Start-Process -FilePath "msiexec.exe" -ArgumentList "/i `"$crdPath`" /qn /norestart" -Wait
          
          # Beri waktu beberapa detik agar instalasi CRD benar-benar selesai
          Write-Host "Waiting for CRD installation to finalize..."
          Start-Sleep -Seconds 15

      - name: Rename Runner User to AiraaCheisyaa and Set Password
        shell: pwsh
        run: |
          # SETELAH instalasi berhasil, baru ubah identitas pengguna
          $password = if ($env:CRD_USER_PASSWORD -and $env:CRD_USER_PASSWORD.Trim() -ne "") { $env:CRD_USER_PASSWORD } else { "ChangeThisPassword123!" }
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          
          Write-Host "Renaming 'runneradmin' to 'AiraaCheisyaa'..."
          Rename-LocalUser -Name "runneradmin" -NewName "AiraaCheisyaa"
          
          Write-Host "Setting password for 'AiraaCheisyaa'..."
          Set-LocalUser -Name "AiraaCheisyaa" -Password $securePass

          echo "WINDOWS_PASSWORD=$password" >> $env:GITHUB_ENV

      - name: Start CRD in Current Session (now as AiraaCheisyaa)
        shell: pwsh
        run: |
          Write-Host "Verifying current user is now AiraaCheisyaa..."
          Write-Host "Current user: $env:UserName" # Ini mungkin masih menampilkan runneradmin, tapi nama logonnya sudah AiraaCheisyaa

          $FullCommand = '${{ github.event.inputs.crd_full_command }}'
          $ArgsPattern = '\s+--code.+'
          if ($FullCommand -match $ArgsPattern) { $crdArgs = $matches[0].Trim() }
          else { Write-Error "Could not extract arguments from input."; exit 1 }

          $crdExePath = (Get-ChildItem -Path "C:\Program Files\Google" -Filter "remoting_start_host.exe" -Recuse -ErrorAction SilentlyContinue | Select-Object -First 1).FullName
          if (-not $crdExePath) {
            Write-Error "FATAL: remoting_start_host.exe not found after installation."
            exit 1
          }

          $PIN = "123456"
          $finalArgs = "$crdArgs -pin=`"$PIN`""
          
          Write-Host "Starting CRD host directly in the current session..."
          Start-Process -FilePath $crdExePath -ArgumentList $finalArgs

          Start-Sleep -Seconds 10
          Write-Host "----------------------------------------"
          Write-Host "Windows User: AiraaCheisyaa"
          Write-Host "CRD PIN: $PIN"
          Write-Host "----------------------------------------"

      - name: Keep-Runner-Alive
        shell: pwsh
        run: |
          Write-Host "Workflow will now stay running up to the job timeout."
          Start-Sleep -Seconds 258000
