name: AiraaCheisyaa CRD (VirtualBox & Performance Boost + Debian ISO)

on:
  workflow_dispatch:
    inputs:
      crd_full_command:
        description: 'Salin dan tempel SELURUH perintah dari halaman CRD Headless (CMD atau PowerShell)'
        required: true

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 4320
    env:
      CRD_USER_PASSWORD: ${{ secrets.CRD_USER_PASSWORD }}
      INSTALLER_CACHE_PATH: C:\cached-installers
      DEBIAN_ISO_FILENAME: debian-13.1.0-amd64-DVD-1.iso

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Cached Installers and ISO
        id: cache-restore
        uses: actions/cache@v4
        with:
          path: ${{ env.INSTALLER_CACHE_PATH }}
          key: ${{ runner.os }}-installers-v2-${{ env.DEBIAN_ISO_FILENAME }}

      - name: Rename Runner User to AiraaCheisyaa and Set Password
        shell: pwsh
        run: |
          $password = if ($env:CRD_USER_PASSWORD -and $env:CRD_USER_PASSWORD.Trim() -ne "") { $env:CRD_USER_PASSWORD } else { "ChangeThisPassword123!" }
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          Write-Host "Mengganti nama pengguna 'runneradmin' menjadi 'AiraaCheisyaa'..."
          Rename-LocalUser -Name "runneradmin" -NewName "AiraaCheisyaa"
          Write-Host "Mengatur kata sandi untuk 'AiraaCheisyaa'..."
          Set-LocalUser -Name "AiraaCheisyaa" -Password $securePass
          echo "WINDOWS_PASSWORD=$password" >> $env:GITHUB_ENV

      - name: Prepare directories
        shell: pwsh
        run: |
          New-Item -Path C:\AiraaCheisyaa -ItemType Directory -Force | Out-Null
          New-Item -Path C:\AiraaCheisyaa\ISO -ItemType Directory -Force | Out-Null
          New-Item -Path C:\AiraaCheisyaa\logs -ItemType Directory -Force | Out-Null
          if (-not (Test-Path "${{ env.INSTALLER_CACHE_PATH }}")) {
            New-Item -Path "${{ env.INSTALLER_CACHE_PATH }}" -ItemType Directory -Force | Out-Null
          }

      - name: Set custom Windows wallpaper (For Current User)
        shell: pwsh
        run: |
          $wallpaperUrl = "https://files.catbox.moe/dqwzph.png"
          $wallpaperPath = "C:\AiraaCheisyaa\wallpaper.png"
          Invoke-WebRequest -Uri $wallpaperUrl -OutFile $wallpaperPath -UseBasicParsing
          Add-Type -TypeDefinition @"
          using System.Runtime.InteropServices;
          public class Wallpaper {
            [DllImport("user32.dll", SetLastError = true, CharSet = CharSet.Auto)]
            public static extern int SystemParametersInfo(int uAction, int uParam, string lpvParam, int fuWinIni);
          }
          "@
          [Wallpaper]::SystemParametersInfo(20, 0, $wallpaperPath, 3)
          Write-Host "Wallpaper telah diatur untuk sesi saat ini."

      - name: Download Debian ISO (uses cache)
        shell: pwsh
        run: |
          $isoUrl = "https://cdimage.debian.org/debian-cd/current/amd64/iso-dvd/${{ env.DEBIAN_ISO_FILENAME }}"
          $cachedIsoPath = Join-Path "${{ env.INSTALLER_CACHE_PATH }}" "${{ env.DEBIAN_ISO_FILENAME }}"
          $finalIsoPath = "C:\AiraaCheisyaa\ISO\${{ env.DEBIAN_ISO_FILENAME }}"
          if (Test-Path $cachedIsoPath) {
              Write-Host "ISO found in cache. Copying to destination..."
              Copy-Item -Path $cachedIsoPath -Destination $finalIsoPath -Force
          } else {
              Write-Host "ISO not found in cache. Starting download..."
              Invoke-WebRequest -Uri $isoUrl -OutFile $cachedIsoPath -UseBasicParsing
              Copy-Item -Path $cachedIsoPath -Destination $finalIsoPath -Force
          }
          Write-Host "Debian ISO is ready at $finalIsoPath"

      - name: Install Pre-requisite Software (uses cache)
        shell: pwsh
        run: |
          $vscodePath = Join-Path "${{ env.INSTALLER_CACHE_PATH }}" "vscode_installer.exe"
          $vboxPath = Join-Path "${{ env.INSTALLER_CACHE_PATH }}" "virtualbox_installer.exe"
          $crdPath = Join-Path "${{ env.INSTALLER_CACHE_PATH }}" "crd.msi"
          if (-not (Test-Path $vscodePath)) { Invoke-WebRequest -Uri "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user" -OutFile $vscodePath }
          Start-Process -FilePath $vscodePath -ArgumentList '/verysilent /mergetasks=!runcode' -Wait
          if (-not (Test-Path $vboxPath)) { Invoke-WebRequest -Uri "https://download.virtualbox.org/virtualbox/7.0.18/VirtualBox-7.0.18-162988-Win.exe" -OutFile $vboxPath }
          Start-Process -FilePath $vboxPath -ArgumentList '--silent --ignore-reboot' -Wait
          if (-not (Test-Path $crdPath)) { Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile $crdPath }
          Start-Process -FilePath "msiexec.exe" -ArgumentList "/i `"$crdPath`" /qn /norestart" -Wait

      - name: '🚀 Apply Performance Tweaks & Optimizations'
        shell: pwsh
        run: |
          Write-Host "Applying system optimizations for a smoother RDP experience..."
          try { powercfg /s SCHEME_MIN } catch { Write-Warning "powercfg tweak failed: $_" }
          try { Set-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects' -Name 'VisualFxSetting' -Value 2 -ErrorAction SilentlyContinue } catch {}
          Get-Service -Name wuauserv -ErrorAction SilentlyContinue | ForEach-Object { Stop-Service -InputObject $_ -Force -ErrorAction SilentlyContinue; Set-Service -Name $_.Name -StartupType Disabled }
          Get-Service -Name WSearch -ErrorAction SilentlyContinue | ForEach-Object { Stop-Service -InputObject $_ -Force -ErrorAction SilentlyContinue; Set-Service -Name $_.Name -StartupType Disabled }
          Write-Host "System optimizations applied successfully!"

      - name: Start CRD in Current User Context (AiraaCheisyaa)
        shell: pwsh
        run: |
          $FullCommand = '${{ github.event.inputs.crd_full_command }}'
          $ArgsPattern = '\s+--code.+'
          if ($FullCommand -match $ArgsPattern) {
            $crdArgs = $matches[0].Trim()
            Write-Host "CRD arguments extracted successfully."
          } else {
            Write-Error "Could not extract arguments from the input command. Please paste the full command."
            exit 1
          }

          # 1. OPTIMISASI: Cari direktori Google terlebih dahulu. Ini SANGAT CEPAT.
          Write-Host "Mencari direktori instalasi Google..."
          $googleDirs = Get-ChildItem -Path "C:\Program Files", "C:\Program Files (x86)" -Filter "Google" -Directory -ErrorAction SilentlyContinue
          
          if ($null -eq $googleDirs) {
            Write-Error "FATAL: Direktori instalasi Google tidak ditemukan. Instalasi CRD mungkin gagal."
            exit 1
          }

          # 2. Sekarang cari file HANYA di dalam direktori Google yang ditemukan. Ini JAUH LEBIH CEPAT.
          Write-Host "Mencari remoting_start_host.exe di dalam direktori Google..."
          $crdExeFile = Get-ChildItem -Path $googleDirs.FullName -Filter "remoting_start_host.exe" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1
          
          if ($null -eq $crdExeFile) {
            Write-Error "FATAL: remoting_start_host.exe tidak dapat ditemukan di dalam direktori Google! Instalasi CRD mungkin gagal."
            exit 1
          }
          $crdExePath = $crdExeFile.FullName
          Write-Host "CRD host ditemukan di: $crdExePath"

          $PIN = "123456"
          $finalArgs = "$crdArgs -pin=`"$PIN`""
          
          Write-Host "Starting CRD host directly in the current user session..."
          Start-Process -FilePath $crdExePath -ArgumentList $finalArgs -Wait

          Write-Host "CRD host process started. Waiting for initialization..."
          Start-Sleep -Seconds 10
          
          Write-Host "----------------------------------------"
          Write-Host "Windows User: AiraaCheisyaa"
          Write-Host "CRD PIN: $PIN"
          Write-Host "Debian ISO Path: C:\AiraaCheisyaa\ISO\${{ env.DEBIAN_ISO_FILENAME }}"
          Write-Host "----------------------------------------"

      - name: Keep-Runner-Alive
        shell: pwsh
        run: |
          Write-Host "Workflow will now stay running up to the job timeout."
          Start-Sleep -Seconds 258000

      - name: 🧹 Run Full System Cleanup
        if: always()
        shell: pwsh
        run: |
          Write-Host "--- Starting Full System Cleanup ---"
          Stop-Process -Name "remoting_*" -Force -ErrorAction SilentlyContinue
          Stop-Process -Name "chrome-remote-desktop" -Force -ErrorAction SilentlyContinue
          Remove-Item -Path C:\AiraaCheisyaa -Recurse -Force -ErrorAction SilentlyContinue
          $crdMsiPath = Join-Path "${{ env.INSTALLER_CACHE_PATH }}" "crd.msi"
          if (Test-Path $crdMsiPath) { Start-Process msiexec.exe -ArgumentList "/x `"$crdMsiPath`" /qn" -Wait }
          Remove-Item -Path "C:\ProgramData\Google\Chrome Remote Desktop" -Recurse -Force -ErrorAction SilentlyContinue
          powercfg /s 381b4222-f694-41f0-9685-ff5bb260df2e | Out-Null
          Set-Service -Name wuauserv -StartupType Automatic -ErrorAction SilentlyContinue
          Set-Service -Name WSearch -StartupType Automatic -ErrorAction SilentlyContinue
          Start-Service wuauserv -ErrorAction SilentlyContinue
          Start-Service WSearch -ErrorAction SilentlyContinue
          Write-Host "--- Cleanup Finished ---"
