name: Kairaa RDP Linux

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Install Desktop Environment and RDP Server
        run: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies dbus-x11 x11-xserver-utils
          sudo apt-get install -y xrdp
          echo "exec startxfce4" | sudo tee /etc/xrdp/startwm.sh
          sudo systemctl restart xrdp
          sudo ufw allow 3389/tcp

      - name: Create RDP User with Secure Password
        run: |
          password=$(openssl rand -base64 16)
          sudo useradd -m -s /bin/bash airaacheisyaa
          echo "airaacheisyaa:$password" | sudo chpasswd
          sudo adduser airaacheisyaa sudo
          sudo adduser airaacheisyaa ssl-cert
          
          echo "RDP_USER=airaacheisyaa" >> $GITHUB_ENV
          echo "RDP_PASS=$password" >> $GITHUB_ENV
          
          echo "Pengguna 'airaacheisyaa' berhasil dibuat."

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Establish Tailscale Connection
        run: |
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$GITHUB_RUN_ID
          
          tsIP=""
          retries=0
          while [ -z "$tsIP" ] && [ $retries -lt 10 ]; do
              tsIP=$(tailscale ip -4)
              sleep 5
              retries=$((retries+1))
          done
          
          if [ -z "$tsIP" ]; then
              echo "Gagal mendapatkan alamat IP Tailscale. Keluar."
              exit 1
          fi
          echo "TAILSCALE_IP=$tsIP" >> $GITHUB_ENV
      
      - name: Verify RDP Accessibility
        run: |
          echo "Tailscale IP: ${{ env.TAILSCALE_IP }}"
          
          if ! nc -zv ${{ env.TAILSCALE_IP }} 3389; then
              echo "Koneksi TCP ke port RDP 3389 gagal."
              exit 1
          fi
          echo "Konektivitas TCP berhasil!"

      - name: Maintain Connection
        run: |
          echo -e "\n=== AKSES RDP ==="
          echo "Alamat: ${{ env.TAILSCALE_IP }}"
          echo "Username: ${{ env.RDP_USER }}"
          echo "Password: ${{ env.RDP_PASS }}"
          echo "==================\n"
          
          while true; do
              echo "[$(date)] RDP Aktif - Gunakan Ctrl+C di workflow untuk menghentikan"
              sleep 300
          done
