name: AiraaCheisyaa CRD (Auto Extract Code)

on:
  workflow_dispatch:
    inputs:
      crd_full_command:
        description: 'Salin dan tempel SELURUH perintah dari halaman CRD Headless (CMD atau PowerShell)'
        required: true

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Create User AiraaCheisyaa
        run: |
          $password = "ChangeThisPassword123!"
          New-LocalUser -Name "AiraaCheisyaa" -Password (ConvertTo-SecureString $password -AsPlainText -Force)
          Add-LocalGroupMember -Group "Administrators" -Member "AiraaCheisyaa"
          echo "WINDOWS_PASSWORD=$password" >> $env:GITHUB_ENV

      - name: Download and Install Chrome Remote Desktop
        run: |
          Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "crd.msi"
          Start-Process msiexec.exe -Wait -ArgumentList '/i crd.msi /qn'
      
      - name: Extract Code and Start Chrome Remote Desktop Host
        run: |
          # Mengambil seluruh perintah yang Anda tempel dari input
          $FullCommand = '${{ github.event.inputs.crd_full_command }}'
          
          # Pola untuk mencari kode di antara --code="..."
          $Pattern = '--code="(.+?)"'
          
          $AuthCode = ""
          if ($FullCommand -match $Pattern) {
              # Jika pola ditemukan, ambil kodenya
              $AuthCode = $matches[1]
              Write-Host "Authorization code extracted successfully."
          } else {
              # Jika pola tidak ditemukan, gagalkan alur kerja
              Write-Error "Could not find authorization code in the provided command. Please paste the full command."
              exit 1
          }
          
          # Menjalankan perintah dengan kode yang sudah diekstrak
          $PIN = "123456"
          $HostName = "gh-runner-${{ github.run_id }}"
          & "C:\Program Files (x86)\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="$AuthCode" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name="$HostName" -pin="$PIN"
          
          Write-Host "=========================== CREDENTIALS ==========================="
          Write-Host "Host Name: $HostName"
          Write-Host "Windows User: AiraaCheisyaa"
          Write-Host "Windows Password: $env:WINDOWS_PASSWORD"
          Write-Host "CRD PIN: $PIN"
          Write-Host "====================================================================="

      - name: Keep Runner Alive
        run: Start-Sleep -Seconds 21000 # Keep alive for ~5.8 hours
