name: Kairaa CRD Linux

on:
  workflow_dispatch:
    inputs:
      crd_auth_code:
        description: 'Tempel Kode Otorisasi CRD untuk Debian Linux di sini'
        required: true
        type: string

jobs:
  secure-crd:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CRD, Desktop Environment, and All Dependencies
        run: |
          # Perbarui daftar paket
          sudo apt-get update
          
          # Unduh paket Chrome Remote Desktop
          wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
          
          # --- PERBAIKAN: Gunakan 'apt install' untuk menangani dependensi secara otomatis ---
          # Ini adalah cara yang benar dan modern untuk menginstal file .deb lokal.
          # apt akan secara otomatis menemukan, mengunduh, dan menginstal semua
          # dependensi yang hilang (seperti policykit-1, xserver, dll.).
          sudo apt install --assume-yes ./chrome-remote-desktop_current_amd64.deb
          
          # Instal lingkungan desktop XFCE yang ringan
          sudo apt install --assume-yes xfce4 desktop-base dbus-x11 xscreensaver
          
          echo "Instalasi CRD dan XFCE beserta semua dependensi selesai."

      - name: Configure and Authorize Chrome Remote Desktop
        run: |
          # Dapatkan nama pengguna bawaan (yaitu 'runner')
          CRD_USER=$(whoami)
          echo "Mengkonfigurasi untuk pengguna: $CRD_USER"

          # Tentukan XFCE sebagai sesi desktop default untuk CRD
          echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" | sudo tee /home/$CRD_USER/.chrome-remote-desktop-session
          
          # Berikan izin yang benar pada file sesi
          sudo chown $CRD_USER:$CRD_USER /home/$CRD_USER/.chrome-remote-desktop-session
          
          # Ambil kode dari input workflow dan jalankan perintah otorisasi
          CRD_AUTH_CODE="${{ github.event.inputs.crd_auth_code }}"
          sudo -u $CRD_USER bash -c "crd-auth --code='$CRD_AUTH_CODE'"

          echo "Otorisasi CRD berhasil."

      - name: Start Chrome Remote Desktop Service
        run: |
          # Mulai layanan CRD
          sudo systemctl start chrome-remote-desktop@$USER
          echo "Layanan Chrome Remote Desktop telah dimulai."
          
      - name: Maintain Connection
        run: |
          echo -e "\n===================================================================="
          echo "  VM ANDA SEKARANG SIAP DIAKSES"
          echo ""
          echo "  1. Buka browser Anda dan pergi ke:"
          echo "     https://remotedesktop.google.com/access"
          echo ""
          echo "  2. Anda akan melihat runner GitHub ini muncul sebagai mesin online."
          echo ""
          echo "  3. Klik untuk terhubung!"
          echo "====================================================================\n"

          # Jaga agar runner tetap aktif
          sleep 21600
