name: Kairaa RDP Linux

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Install Desktop Environment and RDP Server
        run: |
          sudo apt-get update
          sudo apt-get install -y xfce4 xfce4-goodies dbus-x11 x11-xserver-utils
          sudo apt-get install -y xrdp
          echo "exec startxfce4" | sudo tee /etc/xrdp/startwm.sh
          # Tambahkan jeda singkat untuk memastikan service siap sebelum direstart
          sleep 2
          sudo systemctl restart xrdp
          sudo ufw allow 3389/tcp
          echo "Server RDP dan Desktop Environment berhasil diinstal."

      - name: Create RDP User with Secure and Reliable Password
        run: |
          # --- PERBAIKAN INOVATIF: Membuat password yang aman untuk disalin ---
          # Menghasilkan password 16 karakter yang hanya terdiri dari huruf dan angka.
          # Ini menghindari masalah dengan karakter spesial (+, /, =) saat copy-paste.
          password=$(LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 16)
          
          # Membuat pengguna
          sudo useradd -m -s /bin/bash airaacheisyaa
          echo "airaacheisyaa:$password" | sudo chpasswd
          
          # Menambahkan pengguna ke grup yang diperlukan
          sudo adduser airaacheisyaa sudo
          sudo adduser airaacheisyaa ssl-cert
          
          # --- PENINGKATAN: Memastikan izin direktori home benar ---
          sudo chown -R airaacheisyaa:airaacheisyaa /home/airaacheisyaa
          
          echo "RDP_USER=airaacheisyaa" >> $GITHUB_ENV
          echo "RDP_PASS=$password" >> $GITHUB_ENV
          
          # --- PENINGKATAN: Verifikasi bahwa pengguna telah dibuat ---
          echo "Verifikasi pengguna..."
          if getent passwd airaacheisyaa > /dev/null; then
            echo "Pengguna 'airaacheisyaa' berhasil dibuat dan diverifikasi."
          else
            echo "ERROR: Gagal membuat pengguna 'airaacheisyaa'."
            exit 1
          fi

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Establish Tailscale Connection
        run: |
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-$GITHUB_RUN_ID
          
          tsIP=""
          retries=0
          while [ -z "$tsIP" ] && [ $retries -lt 10 ]; do
              tsIP=$(tailscale ip -4)
              sleep 5
              retries=$((retries+1))
          done
          
          if [ -z "$tsIP" ]; then
              echo "Gagal mendapatkan alamat IP Tailscale. Keluar."
              exit 1
          fi
          echo "TAILSCALE_IP=$tsIP" >> $GITHUB_ENV
      
      - name: Verify RDP Accessibility
        run: |
          echo "Tailscale IP: ${{ env.TAILSCALE_IP }}"
          
          # Beri jeda 5 detik sebelum tes koneksi untuk memastikan semua service siap
          echo "Menunggu 5 detik sebelum memverifikasi port RDP..."
          sleep 5
          
          if ! nc -zv ${{ env.TAILSCALE_IP }} 3389; then
              echo "Koneksi TCP ke port RDP 3389 gagal."
              exit 1
          fi
          echo "Konektivitas TCP berhasil!"

      - name: Maintain Connection
        run: |
          echo -e "\n=== AKSES RDP ==="
          echo "Alamat: ${{ env.TAILSCALE_IP }}"
          echo "Username: ${{ env.RDP_USER }}"
          echo "Password: ${{ env.RDP_PASS }}"
          echo "==================\n"
          
          while true; do
              echo "[$(date)] RDP Aktif - Gunakan Ctrl+C di workflow untuk menghentikan"
              sleep 300
          done
