name: Kairaa CRD Linux

on:
  workflow_dispatch:
    inputs:
      crd_auth_code:
        description: 'Tempel Kode Otorisasi CRD untuk Debian Linux di sini'
        required: true
        type: string

jobs:
  secure-crd:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Chrome Remote Desktop and Desktop Environment
        run: |
          # Perbarui daftar paket dan instal dependensi
          sudo apt-get update
          sudo apt-get install --assume-yes wget software-properties-common
          
          # Unduh dan instal Chrome Remote Desktop
          wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
          sudo dpkg --install chrome-remote-desktop_current_amd64.deb
          # Perbaiki dependensi yang mungkin hilang
          sudo apt-get install --assume-yes --fix-broken
          
          # Instal lingkungan desktop XFCE yang ringan
          sudo apt-get install --assume-yes xfce4 desktop-base dbus-x11 xscreensaver
          
          echo "Instalasi CRD dan XFCE selesai."

      - name: Configure and Authorize Chrome Remote Desktop
        run: |
          # Dapatkan nama pengguna bawaan (yaitu 'runner')
          CRD_USER=$(whoami)
          echo "Mengkonfigurasi untuk pengguna: $CRD_USER"

          # Tentukan XFCE sebagai sesi desktop default untuk CRD
          # Perintah ini akan membuat file yang memberitahu CRD untuk memulai XFCE
          echo "exec /etc/X11/Xsession /usr/bin/xfce4-session" | sudo tee /home/$CRD_USER/.chrome-remote-desktop-session
          
          # Berikan izin yang benar pada file sesi
          sudo chown $CRD_USER:$CRD_USER /home/$CRD_USER/.chrome-remote-desktop-session
          
          # --- INI BAGIAN KUNCI UNTUK OTORISASI HEADLESS ---
          # Ambil kode dari input workflow dan simpan ke variabel
          CRD_AUTH_CODE="${{ github.event.inputs.crd_auth_code }}"
          
          # Jalankan perintah otorisasi CRD sebagai pengguna 'runner'
          # Tanda '--' memastikan argumen setelahnya tidak diinterpretasikan sebagai opsi
          sudo -u $CRD_USER bash -c "crd-auth --code='$CRD_AUTH_CODE'"

          echo "Otorisasi CRD berhasil."

      - name: Start Chrome Remote Desktop Service
        run: |
          # Mulai layanan CRD. Layanan ini akan berjalan di latar belakang.
          # '@%i' akan otomatis digantikan dengan nama pengguna yang menjalankan service.
          sudo systemctl start chrome-remote-desktop@$USER
          echo "Layanan Chrome Remote Desktop telah dimulai."
          
      - name: Maintain Connection
        run: |
          echo -e "\n===================================================================="
          echo "  VM ANDA SEKARANG SIAP DIAKSES"
          echo ""
          echo "  1. Buka browser Anda dan pergi ke:"
          echo "     https://remotedesktop.google.com/access"
          echo ""
          echo "  2. Anda akan melihat runner GitHub ini muncul sebagai mesin online."
          echo "     (Nama host akan terlihat seperti 'gh-runner-...') "
          echo ""
          echo "  3. Klik untuk terhubung!"
          echo "====================================================================\n"

          # Jaga agar runner tetap aktif selama 6 jam
          sleep 21600
