name: AiraaCheisyaa CRD

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Create User AiraaCheisyaa
        run: |
          $password = "ChangeThisPassword123!"
          $securePass = ConvertTo-SecureString $password -AsPlainText -Force
          New-LocalUser -Name "AiraaCheisyaa" -Password $securePass -FullName "AiraaCheisyaa" -Description "User for CRD"
          Add-LocalGroupMember -Group "Administrators" -Member "AiraaCheisyaa"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "AiraaCheisyaa"
          echo "WINDOWS_USER=AiraaCheisyaa" >> $env:GITHUB_ENV
          echo "WINDOWS_PASSWORD=$password" >> $env:GITHUB_ENV

      - name: Download and Install Chrome Remote Desktop
        run: |
          Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "crd_installer.msi"
          Start-Process msiexec.exe -Wait -ArgumentList '/i crd_installer.msi /qn'

      - name: Generate CRD Setup Command
        run: |
          $PIN = "123456" # Anda bisa mengubah PIN default ini
          $HostName = "gh-runner-${{ github.run_id }}"
          $CRD_Command = '& "C:\Program Files (x86)\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="PASTE_YOUR_AUTH_CODE_HERE" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name="' + $HostName + '" -pin="' + $PIN + '"'
          
          echo "CRD_SETUP_COMMAND=${CRD_Command}" >> $env:GITHUB_ENV
          echo "CRD_PIN=${PIN}" >> $env:GITHUB_ENV

      - name: Display Connection Info and Keep Alive
        run: |
          Write-Host "========================= SETUP INSTRUCTIONS ========================="
          Write-Host "1. Go to: https://remotedesktop.google.com/headless"
          Write-Host "2. Sign in and click 'Begin', then 'Next', then 'Authorize'."
          Write-Host "3. You will get a command for Windows (cmd). Copy ONLY the authorization code."
          Write-Host "   It looks like this: 4/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
          Write-Host ""
          Write-Host "4. You will need to access the runner to run the final command."
          Write-Host "   (For example, using a 'debug over tmate' step if you add one)."
          Write-Host ""
          Write-Host "5. In a PowerShell terminal on the runner, run the command below"
          Write-Host "   after replacing 'PASTE_YOUR_AUTH_CODE_HERE' with your code:"
          Write-Host ""
          Write-Host "${{ env.CRD_SETUP_COMMAND }}"
          Write-Host ""
          Write-Host "=========================== CREDENTIALS ==========================="
          Write-Host "Windows User: ${{ env.WINDOWS_USER }}"
          Write-Host "Windows Password: ${{ env.WINDOWS_PASSWORD }}"
          Write-Host "CRD PIN: ${{ env.CRD_PIN }}"
          Write-Host "====================================================================="
          
          # Keep runner active until manually cancelled
          while ($true) {
            Start-Sleep -Seconds 300
            Write-Host "[$(Get-Date)] Keeping runner alive for Chrome Remote Desktop session."
          }
